<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'ProductID' => 1,
                'ProductName' => 'Chai',
                'SupplierID' => 1,
                'CategoryID' => 1,
                'QuantityPerUnit' => '10 boxes x 20 bags',
                'UnitPrice' => 18.00,
                'UnitsInStock' => 39,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 10,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 2,
                'ProductName' => 'Chang',
                'SupplierID' => 1,
                'CategoryID' => 1,
                'QuantityPerUnit' => '24 - 12 oz bottles',
                'UnitPrice' => 19.00,
                'UnitsInStock' => 17,
                'UnitsInOrder' => 40,
                'ReorderLevel' => 25,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 3,
                'ProductName' => 'Aniseed Syrup',
                'SupplierID' => 1,
                'CategoryID' => 2,
                'QuantityPerUnit' => '12 - 550 ml bottles',
                'UnitPrice' => 10.00,
                'UnitsInStock' => 13,
                'UnitsInOrder' => 70,
                'ReorderLevel' => 25,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 4,
                'ProductName' => "Chef Anton's Cajun Seasoning",
                'SupplierID' => 2,
                'CategoryID' => 2,
                'QuantityPerUnit' => '48 - 6 oz jars',
                'UnitPrice' => 22.00,
                'UnitsInStock' => 53,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 0,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 5,
                'ProductName' => "Chef Anton's Gumbo Mix",
                'SupplierID' => 2,
                'CategoryID' => 2,
                'QuantityPerUnit' => '36 boxes',
                'UnitPrice' => 21.35,
                'UnitsInStock' => 0,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 0,
                'Discontinued' => 1,
            ],
            [
                'ProductID' => 6,
                'ProductName' => "Grandma's Boysenberry Spread",
                'SupplierID' => 3,
                'CategoryID' => 2,
                'QuantityPerUnit' => '12 - 8 oz jars',
                'UnitPrice' => 25.00,
                'UnitsInStock' => 120,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 25,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 7,
                'ProductName' => "Uncle Bob's Organic Dried Pears",
                'SupplierID' => 3,
                'CategoryID' => 7,
                'QuantityPerUnit' => '12 - 1 lb pkgs.',
                'UnitPrice' => 30.00,
                'UnitsInStock' => 15,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 10,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 8,
                'ProductName' => 'Northwoods Cranberry Sauce',
                'SupplierID' => 3,
                'CategoryID' => 2,
                'QuantityPerUnit' => '12 - 12 oz jars',
                'UnitPrice' => 40.00,
                'UnitsInStock' => 6,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 0,
                'Discontinued' => 0,
            ],
            [
                'ProductID' => 9,
                'ProductName' => 'Mishi Kobe Niku',
                'SupplierID' => 4,
                'CategoryID' => 6,
                'QuantityPerUnit' => '18 - 500 g pkgs.',
                'UnitPrice' => 97.00,
                'UnitsInStock' => 29,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 0,
                'Discontinued' => 1,
            ],
            [
                'ProductID' => 10,
                'ProductName' => 'Ikura',
                'SupplierID' => 4,
                'CategoryID' => 8,
                'QuantityPerUnit' => '12 - 200 ml jars',
                'UnitPrice' => 31.00,
                'UnitsInStock' => 31,
                'UnitsInOrder' => 0,
                'ReorderLevel' => 0,
                'Discontinued' => 0,
            ],
        ]);
    }
}